### PR TITLE
Adding in the EC2 Spot hibernation agent.

### PR DESCRIPTION
**Pull request by JasonSwindle**
Adding spot(ie) support to the template.

### CODE REVIEW

**Comment by PaulMaddox** [comment]
Thanks Jason, this is great. I think we should call this out in the README though.

Something along the lines of "To enable spot pricing for your cluster you will need to.... if you do this the default behaviour on termination notification is...."

**Comment by JasonSwindle** [comment]
Howdy,

This is the first of many PRs coming, just laying some of the ground-work for @O1moore work. I will work on a PR for the readme as well, good call out.

**Review by JasonSwindle — COMMENTED** [review]
Should address #50

**Comment by PaulMaddox** [comment]
Thanks - as soon as you can update this PR to include the README changes we're good to merge.

**Comment by JasonSwindle** [comment]
Ok, I think my update now covers what you want.  I think.

**Review by PaulMaddox — APPROVED** [review]

**Pull request merged**
