### PR TITLE
Update AMIs

### PR DESCRIPTION
**Pull request by MatteCarra**

### CODE REVIEW

**Comment by wichert** [comment]
To what version are you updating? You did not change the comment which still mentions amzn-ami-2016.09.f-amazon-ecs-optimized. 

FWIW I've found the latest set of versions to be quite unstable.

**Comment by MatteCarra** [comment]
I didn't know that latest AMI was unstable.
I simply saw on aws the notification that I was using an old AMI and I thought it would have been useful for everyone to have the lastest AMIs.

**Comment by wichert** [comment]
The last one seems reasonable so far, but for a template for people new to ECS it may be better to be slow with updates. 2017.03.a-c were pretty terrible in my experience.

**Comment by wichert** [comment]
FWIW 2017.03.e has been released last week as well.

**Pull request merged**
