### PR TITLE
Added Bastion Host and Volume Support on secondary Block Device

### PR DESCRIPTION
**Pull request by NightKhaos**
This pull request adds a Bastion host so customers are able to SSH into their instances to see what is going on. It also changes the LaunchConfiguration to use a Replacement Update rather than a Rolling Update, and adds a Secondary Block Device to the ECS clusters to be used for volume storage.

### CODE REVIEW

**Comment by PaulMaddox** [comment]
Thanks for submitting this. I'm out on vacation this week but will review this in full when I'm back next week.

**Comment by fantapop** [comment]
Any plan to merge this in?

**Comment by NightKhaos** [comment]
Will need to rework this pull request to include changes to architecture diagram, etc, after discussions with @PaulMaddox. Have been busy of late so haven't been able to revise PR. Keeping open for now.

**Comment by mmautner** [comment]
This would probably be better as two separate pull requests:

1. adding the bastion server and
2. adding the volume stuff

I'm personally more interested in the former than the latter

**Comment by wichert** [comment]
It may also be interesting to do the bastion as an ECS service to save the cost of a mostly unused extra EC2 instance.

**Comment by dougtoppin** [comment]
I have been interested in access to the ecs instances as well and was looking at adding a bastion host to the template when I saw this. I was wondering as an alternative to the bastion if using SSM (and run command) would work well enough? I use SSM pretty successfully and it has the advantages of providing more security (than enabling ssh access) and no additional instance. It does mean adding the related policy and installing the agent through.

I made the following mods to the templates and just had the ecs instances appear as managed instances after the stack creation successfully completed:

* ecs-cluster.yaml - added ssm related policy items, install amazon-ssm-agent.rpm
* master.yaml - point to my template files

Any opinions on whether or not SSM is a reasonable alternative to a bastion in general?

**Comment by PaulMaddox** [comment]
Closing down this PR as SSM support negates the need for a bastian host in most cases.

**Pull request closed without merging**
