### PR TITLE
Updated AMIs

### PR DESCRIPTION
**Pull request by StevenAskwith**
#86 

# amzn-ami-2018.03.h-amazon-ecs-optimized
Nov 2018

* ECS agent: 1.21.0
* Docker: 18.06.1-ce
* ecs-init: 1.21.0-1

### CODE REVIEW

**Comment by mrichman** [comment]
Why not just use the SSM parameter for the latest AMI? I don’t hardcode them anymore.

**Comment by StevenAskwith** [comment]
I agree, but for a one click deployment of a ref architecture you are always going to want to have AMIs in the template to enable that.  
Possibly a slicker solution to this would be to create the SSM parameter in the CFN and populate it from the mapping table or a custom CFN/Lambda to look up the latest value; but for the sake of simplicity in a Ref Arch the mapping does the job.

**Comment by mrichman** [comment]
Just use this as a CFN template parameter. You’ll never need to map an AMI again:

```
ECSAMI:
        Description: ECS-Optimized AMI ID
        Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
        Default: /aws/service/ecs/optimized-ami/amazon-linux/recommended/image_id
```

**Comment by StevenAskwith** [comment]
@mrichman win :) 
I'll update and create a new pull request

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/retrieve-ecs-optimized_AMI.html

**Pull request closed without merging**
